eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
   preferIpAddress: true

microservice:
  payment-service:
    endpoints:
      enpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      enpoint:
        uri: http://ORDER-SERVICE/payment/bookOrder
